### ISSUE TITLE
Mod isn't working (No Connected Text) 

### ISSUE THREAD

**Issue by CmdEngineer** [MasterQ32/BrokenRemote#4]
The Mod shows in the List but failed to load, in the log [()](http://pastebin.com/raw/7ULbv4qj) You can see the problem pretty well but I don't know how to fix it! Please help!

**Comment by ikskuh** [comment]
This seems weird, as the mod could not register itself. Do you have any other mods installed besides BrokenRemote?

**Comment by CmdEngineer** [comment]
I do but it does it also with no other mods installed

**Comment by ikskuh** [comment]
Can you look up the following folder and send a list of the files in there?
`C:\Program Files (x86)\Steam\steamapps\common\The Binding of Isaac Rebirth\resources\scripts`

It seems like the mod loader fails completly (as the main.lua does not load)

**Comment by CmdEngineer** [comment]
I don't have the \scripts folder there The mod is installed in
Documents\My Games\Binding of Isaac Afterbirth+ Mods 
Like all my other mods

**Comment by ikskuh** [comment]
Okay, can you let Steam make a file sanity check? The scripts folder must be there in order to get the game run (it is also there if you don't unpack the resources)

**Comment by CmdEngineer** [comment]
I just run steam Verify Integrity of Game Files? Is this what you ment?
![screenshot_3](https://cloud.githubusercontent.com/assets/19872218/22468270/567362a6-e7d0-11e6-8084-f69458ee3b86.png)
Now that I check the files I have the scripts folder, Should I try re running the mod and stuff?

**Comment by ikskuh** [comment]
Yes, that was what i meant. Now mods should run again ;)

**Comment by CmdEngineer** [comment]
Thank YOU I can see the connected text now! REALLY THANK YOU 👍

**Comment by ikskuh** [comment]
You're welcome.
